# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_files/posgen_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PosGenWindow(object):
    def setupUi(self, PosGenWindow):
        PosGenWindow.setObjectName("PosGenWindow")
        PosGenWindow.resize(766, 747)
        self.posgen_widget = QtWidgets.QWidget(PosGenWindow)
        self.posgen_widget.setObjectName("posgen_widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 371, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.grid_type_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.grid_type_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_type_layout.setObjectName("grid_type_layout")
        self.one_rect_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.one_rect_button.setChecked(True)
        self.one_rect_button.setObjectName("one_rect_button")
        self.grid_type_layout.addWidget(self.one_rect_button)
        self.two_rect_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.two_rect_button.setObjectName("two_rect_button")
        self.grid_type_layout.addWidget(self.two_rect_button)
        self.positions_plot = ImageView(self.posgen_widget)
        self.positions_plot.setGeometry(QtCore.QRect(20, 320, 411, 391))
        self.positions_plot.setObjectName("positions_plot")
        self.gridLayoutWidget = QtWidgets.QWidget(self.posgen_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 130, 200, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.one_side_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.one_side_layout.setContentsMargins(0, 0, 0, 0)
        self.one_side_layout.setObjectName("one_side_layout")
        self.tl_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.tl_button.setObjectName("tl_button")
        self.one_side_layout.addWidget(self.tl_button, 0, 0, 1, 1)
        self.bl_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bl_button.setObjectName("bl_button")
        self.one_side_layout.addWidget(self.bl_button, 1, 0, 1, 1)
        self.tr_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.tr_button.setObjectName("tr_button")
        self.one_side_layout.addWidget(self.tr_button, 0, 1, 1, 1)
        self.br_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.br_button.setObjectName("br_button")
        self.one_side_layout.addWidget(self.br_button, 1, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_2.setEnabled(True)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 130, 526, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.two_sides_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.two_sides_layout.setContentsMargins(0, 0, 0, 0)
        self.two_sides_layout.setObjectName("two_sides_layout")
        self.left_side_layout = QtWidgets.QGridLayout()
        self.left_side_layout.setObjectName("left_side_layout")
        self.left_bl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_bl_button.setEnabled(True)
        self.left_bl_button.setObjectName("left_bl_button")
        self.left_side_layout.addWidget(self.left_bl_button, 1, 0, 1, 1)
        self.left_br_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_br_button.setEnabled(True)
        self.left_br_button.setObjectName("left_br_button")
        self.left_side_layout.addWidget(self.left_br_button, 1, 1, 1, 1)
        self.left_tl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_tl_button.setEnabled(True)
        self.left_tl_button.setObjectName("left_tl_button")
        self.left_side_layout.addWidget(self.left_tl_button, 0, 0, 1, 1)
        self.left_tr_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_tr_button.setEnabled(True)
        self.left_tr_button.setObjectName("left_tr_button")
        self.left_side_layout.addWidget(self.left_tr_button, 0, 1, 1, 1)
        self.two_sides_layout.addLayout(self.left_side_layout)
        self.right_side_layout = QtWidgets.QGridLayout()
        self.right_side_layout.setObjectName("right_side_layout")
        self.right_tr_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_tr_button.setEnabled(True)
        self.right_tr_button.setObjectName("right_tr_button")
        self.right_side_layout.addWidget(self.right_tr_button, 0, 1, 1, 1)
        self.right_tl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_tl_button.setEnabled(True)
        self.right_tl_button.setObjectName("right_tl_button")
        self.right_side_layout.addWidget(self.right_tl_button, 0, 0, 1, 1)
        self.right_bl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_bl_button.setEnabled(True)
        self.right_bl_button.setObjectName("right_bl_button")
        self.right_side_layout.addWidget(self.right_bl_button, 1, 0, 1, 1)
        self.right_br_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_br_button.setEnabled(True)
        self.right_br_button.setObjectName("right_br_button")
        self.right_side_layout.addWidget(self.right_br_button, 1, 1, 1, 1)
        self.two_sides_layout.addLayout(self.right_side_layout)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(400, 10, 298, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.general_buttons = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.general_buttons.setContentsMargins(0, 0, 0, 0)
        self.general_buttons.setObjectName("general_buttons")
        self.update_plot_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.update_plot_button.setObjectName("update_plot_button")
        self.general_buttons.addWidget(self.update_plot_button)
        self.save_pos_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.save_pos_button.setObjectName("save_pos_button")
        self.general_buttons.addWidget(self.save_pos_button)
        self.quit_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quit_button.setObjectName("quit_button")
        self.general_buttons.addWidget(self.quit_button)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 260, 411, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.spacing_layout_input = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.spacing_layout_input.setContentsMargins(0, 0, 0, 0)
        self.spacing_layout_input.setObjectName("spacing_layout_input")
        self.x_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.x_label.setObjectName("x_label")
        self.spacing_layout_input.addWidget(self.x_label)
        self.x_spacing = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.x_spacing.setObjectName("x_spacing")
        self.spacing_layout_input.addWidget(self.x_spacing)
        self.y_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.y_label.setObjectName("y_label")
        self.spacing_layout_input.addWidget(self.y_label)
        self.y_spacing = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.y_spacing.setObjectName("y_spacing")
        self.spacing_layout_input.addWidget(self.y_spacing)
        self.generate_pos_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.generate_pos_button.setObjectName("generate_pos_button")
        self.spacing_layout_input.addWidget(self.generate_pos_button)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 220, 371, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.spacing_layout_type = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.spacing_layout_type.setContentsMargins(0, 0, 0, 0)
        self.spacing_layout_type.setObjectName("spacing_layout_type")
        self.auto_spacing_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.auto_spacing_button.setChecked(True)
        self.auto_spacing_button.setObjectName("auto_spacing_button")
        self.spacing_layout_type.addWidget(self.auto_spacing_button)
        self.manual_spacing_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.manual_spacing_button.setObjectName("manual_spacing_button")
        self.spacing_layout_type.addWidget(self.manual_spacing_button)
        PosGenWindow.setCentralWidget(self.posgen_widget)
        self.menubar = QtWidgets.QMenuBar(PosGenWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 22))
        self.menubar.setObjectName("menubar")
        PosGenWindow.setMenuBar(self.menubar)

        self.retranslateUi(PosGenWindow)
        QtCore.QMetaObject.connectSlotsByName(PosGenWindow)

    def retranslateUi(self, PosGenWindow):
        _translate = QtCore.QCoreApplication.translate
        PosGenWindow.setWindowTitle(_translate("PosGenWindow", "MainWindow"))
        self.one_rect_button.setText(_translate("PosGenWindow", "One Side"))
        self.two_rect_button.setText(_translate("PosGenWindow", "Two sides"))
        self.tl_button.setText(_translate("PosGenWindow", "Top Left"))
        self.bl_button.setText(_translate("PosGenWindow", "Bottom Left"))
        self.tr_button.setText(_translate("PosGenWindow", "Top Right"))
        self.br_button.setText(_translate("PosGenWindow", "Bottom Right"))
        self.left_bl_button.setText(_translate("PosGenWindow", "BL1(left-side)"))
        self.left_br_button.setText(_translate("PosGenWindow", "BR1(left-side)"))
        self.left_tl_button.setText(_translate("PosGenWindow", "TL1(left-side)"))
        self.left_tr_button.setText(_translate("PosGenWindow", "TR1(left-side)"))
        self.right_tr_button.setText(_translate("PosGenWindow", "TR2(right-side)"))
        self.right_tl_button.setText(_translate("PosGenWindow", "TL2(right-side)"))
        self.right_bl_button.setText(_translate("PosGenWindow", "BL2(right-side)"))
        self.right_br_button.setText(_translate("PosGenWindow", "BR2(right-side)"))
        self.update_plot_button.setText(_translate("PosGenWindow", "Update Plot"))
        self.save_pos_button.setText(_translate("PosGenWindow", "Save Positions"))
        self.quit_button.setText(_translate("PosGenWindow", "Quit"))
        self.x_label.setText(_translate("PosGenWindow", "X"))
        self.y_label.setText(_translate("PosGenWindow", "Y"))
        self.generate_pos_button.setText(_translate("PosGenWindow", "Generate Positions"))
        self.auto_spacing_button.setText(_translate("PosGenWindow", "Auto spacing"))
        self.manual_spacing_button.setText(_translate("PosGenWindow", "Manual Spacing"))

from pyqtgraph import ImageView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PosGenWindow = QtWidgets.QMainWindow()
    ui = Ui_PosGenWindow()
    ui.setupUi(PosGenWindow)
    PosGenWindow.show()
    sys.exit(app.exec_())

