# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt_ui_files/posgen_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PosGenWindow(object):
    def setupUi(self, PosGenWindow):
        PosGenWindow.setObjectName("PosGenWindow")
        PosGenWindow.resize(842, 748)
        self.posgen_widget = QtWidgets.QWidget(PosGenWindow)
        self.posgen_widget.setObjectName("posgen_widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 371, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.grid_type_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.grid_type_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_type_layout.setObjectName("grid_type_layout")
        self.one_rect_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.one_rect_button.setObjectName("one_rect_button")
        self.grid_type_layout.addWidget(self.one_rect_button)
        self.two_rect_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.two_rect_button.setObjectName("two_rect_button")
        self.grid_type_layout.addWidget(self.two_rect_button)
        self.graphicsView = ImageView(self.posgen_widget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 260, 551, 441))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayoutWidget = QtWidgets.QWidget(self.posgen_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 120, 200, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.one_side_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.one_side_layout.setContentsMargins(0, 0, 0, 0)
        self.one_side_layout.setObjectName("one_side_layout")
        self.tl_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.tl_button.setObjectName("tl_button")
        self.one_side_layout.addWidget(self.tl_button, 0, 0, 1, 1)
        self.bl_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bl_button.setObjectName("bl_button")
        self.one_side_layout.addWidget(self.bl_button, 1, 0, 1, 1)
        self.tr_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.tr_button.setObjectName("tr_button")
        self.one_side_layout.addWidget(self.tr_button, 0, 1, 1, 1)
        self.br_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.br_button.setObjectName("br_button")
        self.one_side_layout.addWidget(self.br_button, 1, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 100, 526, 131))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.two_sides_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.two_sides_layout.setContentsMargins(0, 0, 0, 0)
        self.two_sides_layout.setObjectName("two_sides_layout")
        self.left_side_layout = QtWidgets.QGridLayout()
        self.left_side_layout.setObjectName("left_side_layout")
        self.left_bl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_bl_button.setObjectName("left_bl_button")
        self.left_side_layout.addWidget(self.left_bl_button, 1, 0, 1, 1)
        self.left_br_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_br_button.setObjectName("left_br_button")
        self.left_side_layout.addWidget(self.left_br_button, 1, 1, 1, 1)
        self.left_tl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_tl_button.setObjectName("left_tl_button")
        self.left_side_layout.addWidget(self.left_tl_button, 0, 0, 1, 1)
        self.left_tr_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_tr_button.setObjectName("left_tr_button")
        self.left_side_layout.addWidget(self.left_tr_button, 0, 1, 1, 1)
        self.two_sides_layout.addLayout(self.left_side_layout)
        self.right_side_layout = QtWidgets.QGridLayout()
        self.right_side_layout.setObjectName("right_side_layout")
        self.right_tr_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_tr_button.setObjectName("right_tr_button")
        self.right_side_layout.addWidget(self.right_tr_button, 0, 1, 1, 1)
        self.right_br_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_br_button.setObjectName("right_br_button")
        self.right_side_layout.addWidget(self.right_br_button, 1, 1, 1, 1)
        self.right_tl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_tl_button.setObjectName("right_tl_button")
        self.right_side_layout.addWidget(self.right_tl_button, 0, 0, 1, 1)
        self.right_bl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_bl_button.setObjectName("right_bl_button")
        self.right_side_layout.addWidget(self.right_bl_button, 1, 0, 1, 1)
        self.two_sides_layout.addLayout(self.right_side_layout)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(400, 10, 298, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.general_buttons = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.general_buttons.setContentsMargins(0, 0, 0, 0)
        self.general_buttons.setObjectName("general_buttons")
        self.update_plot_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.update_plot_button.setObjectName("update_plot_button")
        self.general_buttons.addWidget(self.update_plot_button)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.general_buttons.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.general_buttons.addWidget(self.pushButton_3)
        PosGenWindow.setCentralWidget(self.posgen_widget)
        self.menubar = QtWidgets.QMenuBar(PosGenWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 22))
        self.menubar.setObjectName("menubar")
        PosGenWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PosGenWindow)
        self.statusbar.setObjectName("statusbar")
        PosGenWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PosGenWindow)
        QtCore.QMetaObject.connectSlotsByName(PosGenWindow)

    def retranslateUi(self, PosGenWindow):
        _translate = QtCore.QCoreApplication.translate
        PosGenWindow.setWindowTitle(_translate("PosGenWindow", "MainWindow"))
        self.one_rect_button.setText(_translate("PosGenWindow", "One Side"))
        self.two_rect_button.setText(_translate("PosGenWindow", "Two sides"))
        self.tl_button.setText(_translate("PosGenWindow", "Top Left"))
        self.bl_button.setText(_translate("PosGenWindow", "Bottom Left"))
        self.tr_button.setText(_translate("PosGenWindow", "Top Right"))
        self.br_button.setText(_translate("PosGenWindow", "Bottom Right"))
        self.left_bl_button.setText(_translate("PosGenWindow", "BL1(left)"))
        self.left_br_button.setText(_translate("PosGenWindow", "BR1(left)"))
        self.left_tl_button.setText(_translate("PosGenWindow", "TL1(left)"))
        self.left_tr_button.setText(_translate("PosGenWindow", "TR1(left)"))
        self.right_tr_button.setText(_translate("PosGenWindow", "TR2(right)"))
        self.right_br_button.setText(_translate("PosGenWindow", "BR2(right)"))
        self.right_tl_button.setText(_translate("PosGenWindow", "TL2(right)"))
        self.right_bl_button.setText(_translate("PosGenWindow", "BL2(right)"))
        self.update_plot_button.setText(_translate("PosGenWindow", "Update Plot"))
        self.pushButton_2.setText(_translate("PosGenWindow", "Save Positions"))
        self.pushButton_3.setText(_translate("PosGenWindow", "Quit"))

from pyqtgraph import ImageView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PosGenWindow = QtWidgets.QMainWindow()
    ui = Ui_PosGenWindow()
    ui.setupUi(PosGenWindow)
    PosGenWindow.show()
    sys.exit(app.exec_())

