# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_files/posgen_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PosGenWindow(object):
    def setupUi(self, PosGenWindow):
        PosGenWindow.setObjectName("PosGenWindow")
        PosGenWindow.resize(766, 747)
        self.posgen_widget = QtWidgets.QWidget(PosGenWindow)
        self.posgen_widget.setObjectName("posgen_widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 371, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.grid_type_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.grid_type_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_type_layout.setObjectName("grid_type_layout")
        self.one_rect_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.one_rect_button.setChecked(True)
        self.one_rect_button.setObjectName("one_rect_button")
        self.grid_type_layout.addWidget(self.one_rect_button)
        self.two_rect_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.two_rect_button.setObjectName("two_rect_button")
        self.grid_type_layout.addWidget(self.two_rect_button)
        self.gridLayoutWidget = QtWidgets.QWidget(self.posgen_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 130, 200, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.one_side_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.one_side_layout.setContentsMargins(0, 0, 0, 0)
        self.one_side_layout.setObjectName("one_side_layout")
        self.tl_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.tl_button.setObjectName("tl_button")
        self.one_side_layout.addWidget(self.tl_button, 0, 0, 1, 1)
        self.bl_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bl_button.setObjectName("bl_button")
        self.one_side_layout.addWidget(self.bl_button, 1, 0, 1, 1)
        self.tr_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.tr_button.setObjectName("tr_button")
        self.one_side_layout.addWidget(self.tr_button, 0, 1, 1, 1)
        self.br_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.br_button.setObjectName("br_button")
        self.one_side_layout.addWidget(self.br_button, 1, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_2.setEnabled(True)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 130, 526, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.two_sides_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.two_sides_layout.setContentsMargins(0, 0, 0, 0)
        self.two_sides_layout.setObjectName("two_sides_layout")
        self.left_side_layout = QtWidgets.QGridLayout()
        self.left_side_layout.setObjectName("left_side_layout")
        self.left_bl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_bl_button.setEnabled(True)
        self.left_bl_button.setObjectName("left_bl_button")
        self.left_side_layout.addWidget(self.left_bl_button, 1, 0, 1, 1)
        self.left_br_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_br_button.setEnabled(True)
        self.left_br_button.setObjectName("left_br_button")
        self.left_side_layout.addWidget(self.left_br_button, 1, 1, 1, 1)
        self.left_tl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_tl_button.setEnabled(True)
        self.left_tl_button.setObjectName("left_tl_button")
        self.left_side_layout.addWidget(self.left_tl_button, 0, 0, 1, 1)
        self.left_tr_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.left_tr_button.setEnabled(True)
        self.left_tr_button.setObjectName("left_tr_button")
        self.left_side_layout.addWidget(self.left_tr_button, 0, 1, 1, 1)
        self.two_sides_layout.addLayout(self.left_side_layout)
        self.right_side_layout = QtWidgets.QGridLayout()
        self.right_side_layout.setObjectName("right_side_layout")
        self.right_tr_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_tr_button.setEnabled(True)
        self.right_tr_button.setObjectName("right_tr_button")
        self.right_side_layout.addWidget(self.right_tr_button, 0, 1, 1, 1)
        self.right_tl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_tl_button.setEnabled(True)
        self.right_tl_button.setObjectName("right_tl_button")
        self.right_side_layout.addWidget(self.right_tl_button, 0, 0, 1, 1)
        self.right_bl_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_bl_button.setEnabled(True)
        self.right_bl_button.setObjectName("right_bl_button")
        self.right_side_layout.addWidget(self.right_bl_button, 1, 0, 1, 1)
        self.right_br_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.right_br_button.setEnabled(True)
        self.right_br_button.setObjectName("right_br_button")
        self.right_side_layout.addWidget(self.right_br_button, 1, 1, 1, 1)
        self.two_sides_layout.addLayout(self.right_side_layout)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(400, 10, 298, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.general_buttons = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.general_buttons.setContentsMargins(0, 0, 0, 0)
        self.general_buttons.setObjectName("general_buttons")
        self.update_plot_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.update_plot_button.setObjectName("update_plot_button")
        self.general_buttons.addWidget(self.update_plot_button)
        self.save_pos_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.save_pos_button.setObjectName("save_pos_button")
        self.general_buttons.addWidget(self.save_pos_button)
        self.quit_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.quit_button.setObjectName("quit_button")
        self.general_buttons.addWidget(self.quit_button)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 260, 525, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.spacing_layout_input = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.spacing_layout_input.setContentsMargins(0, 0, 0, 0)
        self.spacing_layout_input.setObjectName("spacing_layout_input")
        self.n_rows_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.n_rows_label.setObjectName("n_rows_label")
        self.spacing_layout_input.addWidget(self.n_rows_label)
        self.n_rows_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.n_rows_edit.setObjectName("n_rows_edit")
        self.spacing_layout_input.addWidget(self.n_rows_edit)
        self.n_cols_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.n_cols_label.setObjectName("n_cols_label")
        self.spacing_layout_input.addWidget(self.n_cols_label)
        self.n_cols_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.n_cols_edit.setObjectName("n_cols_edit")
        self.spacing_layout_input.addWidget(self.n_cols_edit)
        self.generate_pos_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.generate_pos_button.setObjectName("generate_pos_button")
        self.spacing_layout_input.addWidget(self.generate_pos_button)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 220, 371, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.spacing_layout_type = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.spacing_layout_type.setContentsMargins(0, 0, 0, 0)
        self.spacing_layout_type.setObjectName("spacing_layout_type")
        self.auto_spacing_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.auto_spacing_button.setEnabled(False)
        self.auto_spacing_button.setChecked(True)
        self.auto_spacing_button.setObjectName("auto_spacing_button")
        self.spacing_layout_type.addWidget(self.auto_spacing_button)
        self.manual_spacing_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.manual_spacing_button.setEnabled(False)
        self.manual_spacing_button.setObjectName("manual_spacing_button")
        self.spacing_layout_type.addWidget(self.manual_spacing_button)
        self.clear_button = QtWidgets.QPushButton(self.posgen_widget)
        self.clear_button.setGeometry(QtCore.QRect(30, 90, 89, 25))
        self.clear_button.setObjectName("clear_button")
        self.positions_plot = PlotWidget(self.posgen_widget)
        self.positions_plot.setGeometry(QtCore.QRect(30, 350, 341, 311))
        self.positions_plot.setObjectName("positions_plot")
        self.from_file_button = QtWidgets.QPushButton(self.posgen_widget)
        self.from_file_button.setGeometry(QtCore.QRect(140, 90, 89, 25))
        self.from_file_button.setObjectName("from_file_button")
        self.dry_acquire_button = QtWidgets.QPushButton(self.posgen_widget)
        self.dry_acquire_button.setGeometry(QtCore.QRect(510, 420, 89, 25))
        self.dry_acquire_button.setObjectName("dry_acquire_button")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(420, 340, 261, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.save_dir_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.save_dir_layout.setContentsMargins(0, 0, 0, 0)
        self.save_dir_layout.setObjectName("save_dir_layout")
        self.save_dir_path_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.save_dir_path_edit.setEnabled(True)
        self.save_dir_path_edit.setReadOnly(True)
        self.save_dir_path_edit.setObjectName("save_dir_path_edit")
        self.save_dir_layout.addWidget(self.save_dir_path_edit)
        self.save_dir_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.save_dir_button.setObjectName("save_dir_button")
        self.save_dir_layout.addWidget(self.save_dir_button)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.posgen_widget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(420, 370, 261, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exposure_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.exposure_edit.setObjectName("exposure_edit")
        self.horizontalLayout.addWidget(self.exposure_edit)
        self.exposure_label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.exposure_label.setObjectName("exposure_label")
        self.horizontalLayout.addWidget(self.exposure_label)
        self.exposure_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.exposure_button.setObjectName("exposure_button")
        self.horizontalLayout.addWidget(self.exposure_button)
        self.dry_run_progressbar = QtWidgets.QProgressBar(self.posgen_widget)
        self.dry_run_progressbar.setGeometry(QtCore.QRect(420, 460, 261, 23))
        self.dry_run_progressbar.setProperty("value", 0)
        self.dry_run_progressbar.setObjectName("dry_run_progressbar")
        PosGenWindow.setCentralWidget(self.posgen_widget)
        self.menubar = QtWidgets.QMenuBar(PosGenWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 22))
        self.menubar.setObjectName("menubar")
        PosGenWindow.setMenuBar(self.menubar)

        self.retranslateUi(PosGenWindow)
        QtCore.QMetaObject.connectSlotsByName(PosGenWindow)

    def retranslateUi(self, PosGenWindow):
        _translate = QtCore.QCoreApplication.translate
        PosGenWindow.setWindowTitle(_translate("PosGenWindow", "MainWindow"))
        self.one_rect_button.setText(_translate("PosGenWindow", "One Side"))
        self.two_rect_button.setText(_translate("PosGenWindow", "Two sides"))
        self.tl_button.setText(_translate("PosGenWindow", "Top Left"))
        self.bl_button.setText(_translate("PosGenWindow", "Bottom Left"))
        self.tr_button.setText(_translate("PosGenWindow", "Top Right"))
        self.br_button.setText(_translate("PosGenWindow", "Bottom Right"))
        self.left_bl_button.setText(_translate("PosGenWindow", "BL1(left-side)"))
        self.left_br_button.setText(_translate("PosGenWindow", "BR1(left-side)"))
        self.left_tl_button.setText(_translate("PosGenWindow", "TL1(left-side)"))
        self.left_tr_button.setText(_translate("PosGenWindow", "TR1(left-side)"))
        self.right_tr_button.setText(_translate("PosGenWindow", "TR2(right-side)"))
        self.right_tl_button.setText(_translate("PosGenWindow", "TL2(right-side)"))
        self.right_bl_button.setText(_translate("PosGenWindow", "BL2(right-side)"))
        self.right_br_button.setText(_translate("PosGenWindow", "BR2(right-side)"))
        self.update_plot_button.setText(_translate("PosGenWindow", "Update Plot"))
        self.save_pos_button.setText(_translate("PosGenWindow", "Save Positions"))
        self.quit_button.setText(_translate("PosGenWindow", "Quit"))
        self.n_rows_label.setText(_translate("PosGenWindow", "Number of rows"))
        self.n_cols_label.setText(_translate("PosGenWindow", "Number of columns"))
        self.generate_pos_button.setText(_translate("PosGenWindow", "Generate Positions"))
        self.auto_spacing_button.setText(_translate("PosGenWindow", "Auto spacing"))
        self.manual_spacing_button.setText(_translate("PosGenWindow", "Manual Spacing"))
        self.clear_button.setText(_translate("PosGenWindow", "Clear"))
        self.from_file_button.setText(_translate("PosGenWindow", "From File"))
        self.dry_acquire_button.setText(_translate("PosGenWindow", "Dry Acquire"))
        self.save_dir_button.setText(_translate("PosGenWindow", "Save Dir"))
        self.exposure_label.setText(_translate("PosGenWindow", "(ms)"))
        self.exposure_button.setText(_translate("PosGenWindow", "Set Exposure"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PosGenWindow = QtWidgets.QMainWindow()
    ui = Ui_PosGenWindow()
    ui.setupUi(PosGenWindow)
    PosGenWindow.show()
    sys.exit(app.exec_())

