# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_ui_files\tweezer_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TweezerWindow(object):
    def setupUi(self, TweezerWindow):
        TweezerWindow.setObjectName("TweezerWindow")
        TweezerWindow.resize(1551, 709)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TweezerWindow.sizePolicy().hasHeightForWidth())
        TweezerWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(TweezerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setGeometry(QtCore.QRect(1090, 450, 89, 25))
        self.remove_button.setObjectName("remove_button")
        self.show_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_button.setGeometry(QtCore.QRect(990, 450, 89, 25))
        self.show_button.setObjectName("show_button")
        self.undo_button = QtWidgets.QPushButton(self.centralwidget)
        self.undo_button.setGeometry(QtCore.QRect(990, 490, 89, 25))
        self.undo_button.setObjectName("undo_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(1090, 490, 89, 25))
        self.reset_button.setObjectName("reset_button")
        self.image_plot = ImageView(self.centralwidget)
        self.image_plot.setGeometry(QtCore.QRect(20, 110, 541, 561))
        self.image_plot.setObjectName("image_plot")
        self.filter_params_box = QtWidgets.QGroupBox(self.centralwidget)
        self.filter_params_box.setGeometry(QtCore.QRect(610, 80, 341, 261))
        self.filter_params_box.setObjectName("filter_params_box")
        self.formLayoutWidget = QtWidgets.QWidget(self.filter_params_box)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 261, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.frame_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.frame_label.setObjectName("frame_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame_label)
        self.area_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.area_label.setObjectName("area_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.area_label)
        self.fraction_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.fraction_label.setObjectName("fraction_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fraction_label)
        self.area_slider = QtWidgets.QSlider(self.formLayoutWidget)
        self.area_slider.setOrientation(QtCore.Qt.Horizontal)
        self.area_slider.setObjectName("area_slider")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.area_slider)
        self.fraction_slider = QtWidgets.QSlider(self.formLayoutWidget)
        self.fraction_slider.setOrientation(QtCore.Qt.Horizontal)
        self.fraction_slider.setObjectName("fraction_slider")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fraction_slider)
        self.cell_obj_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.cell_obj_label.setObjectName("cell_obj_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cell_obj_label)
        self.cell_obj_slider = QtWidgets.QSlider(self.formLayoutWidget)
        self.cell_obj_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cell_obj_slider.setObjectName("cell_obj_slider")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cell_obj_slider)
        self.frame_slider = QtWidgets.QSlider(self.formLayoutWidget)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_slider)
        self.next_auto_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_auto_button.setGeometry(QtCore.QRect(1090, 530, 89, 25))
        self.next_auto_button.setObjectName("next_auto_button")
        self.send_tweeze_pos_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_tweeze_pos_button.setGeometry(QtCore.QRect(980, 630, 191, 25))
        self.send_tweeze_pos_button.setObjectName("send_tweeze_pos_button")
        self.properties_view = PlotWidget(self.centralwidget)
        self.properties_view.setGeometry(QtCore.QRect(610, 410, 321, 241))
        self.properties_view.setObjectName("properties_view")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 401, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.data_to_fetch = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.data_to_fetch.setContentsMargins(0, 0, 0, 0)
        self.data_to_fetch.setObjectName("data_to_fetch")
        self.pos_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.pos_label.setObjectName("pos_label")
        self.data_to_fetch.addWidget(self.pos_label)
        self.pos_no_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.pos_no_edit.setObjectName("pos_no_edit")
        self.data_to_fetch.addWidget(self.pos_no_edit)
        self.ch_no_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ch_no_label.setObjectName("ch_no_label")
        self.data_to_fetch.addWidget(self.ch_no_label)
        self.ch_no_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ch_no_edit.setObjectName("ch_no_edit")
        self.data_to_fetch.addWidget(self.ch_no_edit)
        self.fetch_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.fetch_button.setObjectName("fetch_button")
        self.data_to_fetch.addWidget(self.fetch_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 60, 491, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.data_to_plot = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.data_to_plot.setContentsMargins(0, 0, 0, 0)
        self.data_to_plot.setObjectName("data_to_plot")
        self.phase_image = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.phase_image.setChecked(True)
        self.phase_image.setObjectName("phase_image")
        self.data_to_plot.addWidget(self.phase_image)
        self.cell_seg_image = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.cell_seg_image.setObjectName("cell_seg_image")
        self.data_to_plot.addWidget(self.cell_seg_image)
        self.cell_tracks_image = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.cell_tracks_image.setObjectName("cell_tracks_image")
        self.data_to_plot.addWidget(self.cell_tracks_image)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(570, 340, 391, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.filter_update = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.filter_update.setContentsMargins(0, 0, 0, 0)
        self.filter_update.setObjectName("filter_update")
        self.update_filters_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.update_filters_button.setObjectName("update_filters_button")
        self.filter_update.addWidget(self.update_filters_button)
        self.find_tweezable_pos_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.find_tweezable_pos_button.setObjectName("find_tweezable_pos_button")
        self.filter_update.addWidget(self.find_tweezable_pos_button)
        self.expt_running_check = QtWidgets.QCheckBox(self.centralwidget)
        self.expt_running_check.setGeometry(QtCore.QRect(460, 20, 131, 23))
        self.expt_running_check.setObjectName("expt_running_check")
        self.active_pos_list = QtWidgets.QListWidget(self.centralwidget)
        self.active_pos_list.setGeometry(QtCore.QRect(970, 10, 256, 421))
        self.active_pos_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.active_pos_list.setObjectName("active_pos_list")
        self.tweeze_pos_list = QtWidgets.QListWidget(self.centralwidget)
        self.tweeze_pos_list.setGeometry(QtCore.QRect(1280, 10, 256, 421))
        self.tweeze_pos_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tweeze_pos_list.setObjectName("tweeze_pos_list")
        self.toTweezeListButton = QtWidgets.QPushButton(self.centralwidget)
        self.toTweezeListButton.setGeometry(QtCore.QRect(1230, 210, 41, 21))
        self.toTweezeListButton.setObjectName("toTweezeListButton")
        self.to_active_list_button = QtWidgets.QPushButton(self.centralwidget)
        self.to_active_list_button.setGeometry(QtCore.QRect(1230, 270, 41, 21))
        self.to_active_list_button.setObjectName("to_active_list_button")
        self.view_active_list_check = QtWidgets.QCheckBox(self.centralwidget)
        self.view_active_list_check.setGeometry(QtCore.QRect(1000, 580, 92, 23))
        self.view_active_list_check.setChecked(True)
        self.view_active_list_check.setObjectName("view_active_list_check")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(620, 10, 230, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.image_show_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.image_show_layout.setContentsMargins(0, 0, 0, 0)
        self.image_show_layout.setObjectName("image_show_layout")
        self.get_last20_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.get_last20_radio.setChecked(True)
        self.get_last20_radio.setObjectName("get_last20_radio")
        self.image_show_layout.addWidget(self.get_last20_radio)
        self.get_all_images_radio = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.get_all_images_radio.setObjectName("get_all_images_radio")
        self.image_show_layout.addWidget(self.get_all_images_radio)
        self.plot_properties_check = QtWidgets.QCheckBox(self.centralwidget)
        self.plot_properties_check.setGeometry(QtCore.QRect(1090, 580, 121, 23))
        self.plot_properties_check.setObjectName("plot_properties_check")
        TweezerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TweezerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1551, 21))
        self.menubar.setObjectName("menubar")
        TweezerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TweezerWindow)
        self.statusbar.setObjectName("statusbar")
        TweezerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TweezerWindow)
        QtCore.QMetaObject.connectSlotsByName(TweezerWindow)

    def retranslateUi(self, TweezerWindow):
        _translate = QtCore.QCoreApplication.translate
        self.remove_button.setText(_translate("TweezerWindow", "Remove"))
        self.show_button.setText(_translate("TweezerWindow", "Show"))
        self.undo_button.setText(_translate("TweezerWindow", "Undo"))
        self.reset_button.setText(_translate("TweezerWindow", "Reset"))
        self.filter_params_box.setTitle(_translate("TweezerWindow", "Filter Parameters"))
        self.frame_label.setText(_translate("TweezerWindow", "Starting Frame No"))
        self.area_label.setText(_translate("TweezerWindow", "Area Threshold"))
        self.fraction_label.setText(_translate("TweezerWindow", "Fraction"))
        self.cell_obj_label.setText(_translate("TweezerWindow", "No of Cell like objects"))
        self.next_auto_button.setText(_translate("TweezerWindow", "Next Auto"))
        self.send_tweeze_pos_button.setText(_translate("TweezerWindow", "Send Tweeze Positions"))
        self.pos_label.setText(_translate("TweezerWindow", "Position"))
        self.ch_no_label.setText(_translate("TweezerWindow", "Channel No"))
        self.fetch_button.setText(_translate("TweezerWindow", "Fetch"))
        self.phase_image.setText(_translate("TweezerWindow", "Phase"))
        self.cell_seg_image.setText(_translate("TweezerWindow", "Cell Seg"))
        self.cell_tracks_image.setText(_translate("TweezerWindow", "Tracking"))
        self.update_filters_button.setText(_translate("TweezerWindow", "Update Filter Parameters"))
        self.find_tweezable_pos_button.setText(_translate("TweezerWindow", "Find All Tweezable Channels"))
        self.expt_running_check.setText(_translate("TweezerWindow", "Is Expt running?"))
        self.toTweezeListButton.setText(_translate("TweezerWindow", ">>"))
        self.to_active_list_button.setText(_translate("TweezerWindow", "<<"))
        self.view_active_list_check.setText(_translate("TweezerWindow", "Active? "))
        self.get_last20_radio.setText(_translate("TweezerWindow", "Last 20 images"))
        self.get_all_images_radio.setText(_translate("TweezerWindow", "All Images"))
        self.plot_properties_check.setText(_translate("TweezerWindow", "Plot Properties"))

from pyqtgraph import ImageView, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TweezerWindow = QtWidgets.QMainWindow()
    ui = Ui_TweezerWindow()
    ui.setupUi(TweezerWindow)
    TweezerWindow.show()
    sys.exit(app.exec_())

