---
# Region detection network training parameters all 
# parameters need, including network hyper parameters
# are written in the is file. It is used to train 
# models for detecting regions on the image that has barcode.

Model:

Save:
  # main directory that stores all the experiment done during training of 
  # the network. Will also be where all the network models and checkpoints
  # are stored
  directory: '/home/pk/Documents/REALTIME/network_expts/barcode_expts' 

Datasets:
  directory: '/home/pk/Documents/REALTIME/data/barcode_yolo'
  type:

  # we use the same transformation for all dataset for now.
  # Later add this option when you refactor into each of the
  # traning subsets and add options later, for now we run defaults
  transformations: 
    type: 'YoloAugmentations'

  # You can decide what percentage you want in each of train, validation, test
  # You can also add subsets on which you want to train, by adding stuff to
  # the list, for ex, you might want to train your final models on all the data
  train:
    percentage: 0.7
    subset:
      - 'train'
  validation:
    percentage: 0.15
    subset:
      - 'validation'
  test:
    percentage: 0.15
      - 'test'

  transforms: # transformations depending on the dataset

PreTrain:
  load_params:
  model_file:

Checkpoints:
  load_ckpt: False
  ckpt_filename:

Hardware:
  device: 'cuda:0'
  num_workers: 6
  torch_threads: 6

HyperParameters:
  batch_size: 6
  architecture: 'YOLOv3'
  model_params:
    anchors: 
      number: 9
      sizes:
      - - 19
        - 168
      - - 21
        - 168
      - - 29
        - 178
      - - 11
        - 130
      - - 11
        - 131
      - - 15
        - 165
      - - 6
        - 115
      - - 7
        - 115
      - - 7
        - 125
      strides:
        - - 32
          - 32
        - - 16
          - 16
        - - 8
          - 8



