---
# Region detection network training parameters all 
# parameters need, including network hyper parameters
# are written in the is file. It is used to train 
# models for detecting regions on the image that has barcode.

Model:

Save:
  # main directory that stores all the experiment done during training of 
  # the network. Will also be where all the network models and checkpoints
  # are stored
  directory: '/home/pk/Documents/REALTIME/network_expts/barcode_expts' 

Datasets:
  directory: '/home/pk/Documents/REALTIME/data/barcode_yolo'
  type:

  # we use the same transformation for all dataset for now.
  # Later add this option when you refactor into each of the
  # traning subsets and add options later, for now we run defaults
  transformations: 
    type: 'YoloAugmentations'

  # You can decide what percentage you want in each of train, validation, test
  # You can also add subsets on which you want to train, by adding stuff to
  # the list, for ex, you might want to train your final models on all the data
  train:
    percentage: 0.8
    subset:
      - 'train'
  validation:
    percentage: 0.20
    subset:
      - 'validation'
  test:
    percentage: 0.0
    subset:
      - 'test'

  transforms: # transformations depending on the dataset

PreTrain:
  load_params:
  model_file:

Checkpoints:
  load_ckpt: False
  ckpt_filename:

Hardware:
  device: 'cuda:1'
  num_workers: 6
  torch_threads: 6

HyperParameters:
  train_batch_size: 8
  validation_batch_size: 2
  test_batch_size: 2
  architecture: 'YOLOv3'
  epochs: 50
  optimizer:
    name: 'AdamW'
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0005
  scheduler:
    name: 'CosineWarmup'
    warmup: 10 # number of batches to reach max lr
    max_iters: 100 # total max for cosine to go to zero

  loss: 'yolo_loss'
  model_params:
    num_classes: 1
    anchors: 
      number: 9
      sizes:
      - - 19
        - 168
      - - 21
        - 168
      - - 29
        - 178
      - - 11
        - 130
      - - 11
        - 131
      - - 15
        - 165
      - - 6
        - 115
      - - 7
        - 115
      - - 7
        - 125
      strides:
        - - 32
          - 32
        - - 16
          - 16
        - - 8
          - 8


Testing: # all parameters needed for testing are included in this section,
# This section needs to be self contained and will be read during the test loop of the 
# model
  get_current_model: True # if true, will load the 
  model_path: #
  architecture: 'YOLOv3'
  batch_size: 2
  images_dir_path: 
