---
# Segmentation network training parameters all 
# parameters need, including network hyper parameters
# are written in the is file. It is used to train 
# models for segmentation of cells and channels
Model:

Save:
  directory: '/home/pk/Documents/REALTIME/network_expts/seg_expts' # main direcotry that contains all training runs

Datasets:
  directory: '/home/pk/Documents/REALTIME/data/seg_unet'
  # 'omni_single', 'unet_single', 'omni_dual', 'unet_dual'
  # duals are when you learn channels and cells in the same model
  type:  'unet_single' 
   # Each species data is split into 3 parts train, validation, test.
  train:

  validation:
    - 'validation'
  test:
    - 'test'

  species: 
    - mixed
    - ecoli

  labels_type: 'flows' # flows or labels

  transformations: # write transforms depending on the dataset

Metrics:

PreTrain:
  load_params: False # load a model file and use a pretrainied parameters, default is False
  model_filename: # file used to load pretrained weights of the model

Checkpoints:
  load_ckpt: False # Incase the training stops, we should load from checkpoint and restart
  ckpt_filename: # ckpt filename from which to load the experiment to restart

Hardware:
  device: 'cuda:1' # device on which to train the network
  num_workers: 6 #
  torch_threads: 6


# All network architecture and training related parameters
HyperParameters:
  batch_size: 8
  architecture: 'Unet'
  channels_by_scale:
    - 1
    - 8
    - 16
    - 32
    - 64
    - 128
  num_outputs: 1
  upsample_type: 'transpose_conv'
  feature_fusion_type: 'concat'


Testing:
  Hardware:
    device: 'cuda:1'
    num_workers: 6
    torch_threads: 6

  model_path: None 
  images_dir: '/home/pk/Documents/REALTIME/data/seg_unet/channels/phase'
  save_dir: '/home/pk/Documents/REALTIME/network_expts/seg_test_save'