---
# Segmentation network training parameters all 
# parameters need, including network hyper parameters
# are written in the is file. It is used to train 
# models for segmentation of cells and channels
Model:

Save:
  directory: '/mnt/sda2/Praneeth/REALTIME/network_expts/seg_expts' # main direcotry that contains all training runs

Datasets:
  directory: '/mnt/sda2/Praneeth/REALTIME/data/seg_unet'
  # follow the documentation in datasets for directory structure
  type:  'omni_cells' 
  # 'omni_cells', 'unet_cells', 'omni_dual', 'unet_dual'
  # 'omni_channels', 'unet_channels'
  # duals are when you learn channels and cells in the same model
  # Each species data is split into 3 parts train, validation, test.
  # You can decide which parts you want to include in which steps of
  # training you models, for ex. in the final models, you might want 
  # to train on all the data you have
  train:
    - 'train'
  validation:
    - 'validation'
  test:
    - 'test'

  species: 
    - mixed
    - ecoli

  labels_type: 'flows' # flows or labels

  transforms: # write transforms depending on the dataset

Metrics:

PreTrain:
  load_params: False # load a model file and use a pretrainied parameters, default is False
  model_filename: # file used to load pretrained weights of the model

Checkpoints:
  load_ckpt: False # Incase the training stops, we should load from checkpoint and restart
  ckpt_filename: # ckpt filename from which to load the experiment to restart

Hardware:
  device: 'cuda:0' # device on which to train the network
  num_workers: 6 #
  torch_threads: 6

HyperParameters:
  batch_size: 8
  architecture: 'Unet'
  channels_by_scale:
    - 1
    - 8
    - 16
    - 32
    - 64
    - 128
  num_outputs: 1
  upsample_type: 'transpose_conv'
  feature_fusion_type: 'concat'


